** NOW Check duplicate files
   SCHEDULED: <2026-01-28 10:00>

** NOTE
   - sprawdzić katalog ~/Downloads
   - zobaczyć duplikaty w ~/mapa

** DONE
* Medytacje
** [[file:~/mapa/sesja.org::*]], 12-02-2026

03:55

Siglum: 


*** PANORAMA
Gdzie i kiedy rozgrywa się to wydarzenie?
Jakie osoby w nim występują?

*** SŁOWO KLUCZ

*** OGRODNIK
Co mówią?
Co czynią?

*** MOJE ŻYCIE
Co mnie porusza?

*** MEDYTACJA
Zdania / słowa do medytacji:
Refleksja po medytacji:

*** KONTEMPLACJA
** [2026-02-12 czw 04:34]

Siglum: 


*** PANORAMA
Gdzie i kiedy rozgrywa się to wydarzenie?
Jakie osoby w nim występują?

*** SŁOWO KLUCZ

*** OGRODNIK
Co mówią?
Co czynią?

*** MOJE ŻYCIE
Co mnie porusza?

*** MEDYTACJA
Zdania / słowa do medytacji:
Refleksja po medytacji:

*** KONTEMPLACJA
** [2026-02-12 czw 18:52]

Siglum: Mt 10,34-42


*** PANORAMA
Gdzie i kiedy rozgrywa się to wydarzenie?
Nie wiem
Jakie osoby w nim występują?
Pan Jezus,Jego uczniowie
SŁOWO KLUCZ: być godnym

*** OGRODNIK
Co mówią?
Pan Jezus naucza Apostołów jak żyć by być godnym Pana
Co czynią?

*** MOJE ŻYCIE
Co mnie porusza?Miecz

*** MEDYTACJA
Zdania / słowa do medytacji: Nie przyszedłem nieść pokoju lecz miecz.
1.Czego nie zrobiłem? Nie przyszedłem
2.Nie przyszedłem czego robić? Nie przyszedłem nieść.
3.Czego nie przyszedłem nieść? Nie przyszedłem nieść pokoju
4.A co niesiesz? Nie przyszedłem nieść pokoju, ale miecz

Refleksja po medytacji:
Ten miecz,to wypełnianie woli Boga.

*** KONTEMPLACJA
** [2026-02-13 pią 14:43]

Siglum: Mt 11,1-15


*** PANORAMA
Gdzie i kiedy rozgrywa się to wydarzenie?
Nie wiem

Jakie osoby w nim występują?
Pan Jezus, Jan Chrzciciel, Apostołowie, tłumy, uczniowie Jana Chrzciciela

*** SŁOWO KLUCZ
Jan Chrzciciel

*** OGRODNIK
Co mówią?
Do Pana Jezusa przyszli uczniowie Jana Chrzciciela z pytaniem czy On jest tym który miał przyjść, czy innego mają oczekiwać. Pan w odpowiedzi powiedział im o cudach które się dzieją,
potem zaczął nauczać tłum i Apostołów o Janie Chrzcicielu.
Co czynią?

*** MOJE ŻYCIE
Co mnie porusza? ludzie mocni

*** MEDYTACJA
Zdania / słowa do medytacji: ludzie mocni je zdobywają
1.Kto? ludzie
2.Jacy ludzie? ludzie mocni
3.Co robią ludzie mocni? ludzie mocni zdobywają
4.Co ludzie mocni zdobywają? ludzie mocni je zdobywają

Refleksja po medytacji:
Co to dla mnie znaczy być mocnym?
*** KONTEMPLACJA
** [2026-02-14 sob 09:24]

Siglum: 


*** PANORAMA
Gdzie i kiedy rozgrywa się to wydarzenie?
Jakie osoby w nim występują?

*** SŁOWO KLUCZ

*** OGRODNIK
Co mówią?
Co czynią?

*** MOJE ŻYCIE
Co mnie porusza?

*** MEDYTACJA
Zdania / słowa do medytacji:
Refleksja po medytacji:

*** KONTEMPLACJA
