#+title: Medytacja
#+date: 01-03-2026

Siglum: Mt13,24-30

*** PANORAMA
Gdzie i kiedy rozgrywa się to wydarzenie? W okolicy jeziora
Jakie osoby w nim występują? Pan Jezus, apostołowie,tłumy
Słowo klucz:Królestwo niebieskie

*** OGRODNIK
Co mówią? Pan Jezus naucza swoich uczniów i tłumy w przypowieści o Królestwie niebieskim, które stało się jak
człowiek, który na pole posiał przenice, a w nocy przyszedł nieprzyjaciel i nasiał chwastów. Gdy przyszli słudzy rolnika,
pytając czy usunąć chwast, on im odpowiedział by go zostawili do czasu żniw i wtedy chwast będzie usunięty, a przenica zebrana
do spichlerza.
Co czynią?
Jakie nowe czyny i dzieła Jezusa Chrystusa odkryłeś w tym fragmencie Ewangelii? Nauczanie w przypowieści
Jakie odkryłeś nowe cechy charakteru Pana Jezusa, Jego stylu życia i relacji z Bogiem i z ludźmi?
Jakie odkryłeś słowa i czyny, które świadczą o BÓSTWIE Pana Jezusa? Nauczanie w przypowieści
Kto i w jaki sposób wyznał wiarę w Jego boską naturę?
Jak się modliła ta osoba?
Jak żyła?
Jakie to ma znaczenie dla mojego codziennego życia?

*** MOJE ŻYCIE
Czy moje życie jest podobne do życia Pana Jezusa? Nie, nie jest
W czym jestem podobny do Pana Jezusa? W pragnieniu pełnienia woli Ojca niebieskiego
W czym nie jestem podobny do Pana Jezusa? We wszystkim
Dlaczego nie jestem do Niego podobny? Jestem przywiązany do tego świata
Co mogę zmienić, a co jest ode mnie niezależne? Mniej komputera, więcej książki, spacer
Co chciałbyś zmienić? Mniej komputera, więcej książki, spacer
Od czego możesz zacząć? od dziś
Co mnie porusza? noc

*** MEDYTACJA
Zdania / słowa do medytacji: Kiedy wszyscy spali, przyszedł jego wróg, nasiał chwastu w przenicę i oddalił się.
1.kiedy kto? kiedy wszyscy
2.kiedy co wszyscy robili? kiedy wszyscy spali
3.co się stało kiedy wszyscy spali? kiedy wszyscy spali, przyszedł
4.kto przyszedł kiedy wszyscy spali? kiedy wszyscy spali, przyszedł wróg
5.czyj wróg przyszedł,kiedy wszyscy spali? kiedy wszyscy spali? kiedy wszyscy spali? kiedy wszyscy spali, przyszedł jego wróg
6.co zrobił jego wróg, gdy przyszedł, kiedy wszyscy spali? kiedy wszyscy spali? kiedy wszyscy spali? kiedy wszyscy spali, przyszedł jego wróg i
  nasiał
7.czego nasiał wróg,kiedy przyszedł,kiedy wszyscy spali? kiedy wszyscy spali? kiedy wszyscy spali? kiedy wszyscy spali, przyszedł jego wróg i
  nasiał chwastu
8.gdzie jego wróg nasiał chwastu, kiedy wszyscy spali? kiedy wszyscy spali? kiedy wszyscy spali? kiedy wszyscy spali, przyszedł jego wróg i nasiał
  chwastu w przenicę
9.co zrobił jego wróg po tym jak nasiał chwastu w przenicę kiedy wszyscy spali? kiedy wszyscy spali, przyszedł jego wróg i nasiał chwastu w przenicę i oddalił się.  

Refleksja po medytacji:
Czas modlitwy nocnej którego pragnienie jest ciągle we mnie nie był do tej pory właściwie wykorzystany. To nie znaczy że był zmarnowany,sporzytkowałem go na coś, na co
nie był przeznaczony. To nie jest dobre. Mam nadzieję że Pan obdaży mnie jeszcze darem modlitwy nocnej.
*** KONTEMPLACJA
