
#+title: Medytacja
#+date: 19-02-2026

Siglum: 

*** PANORAMA
Gdzie i kiedy rozgrywa się to wydarzenie?
Nie wiem
Jakie osoby w nim występują?
Pan Jezus,Apostołowie, tłumy
Słowo klucz:
odpoczynek

*** OGRODNIK
Co mówią?
Pan Jezus zachęca Apostołów i tłumy by ci którzy są utrudzeni przyszli do Niego by dał im ulge

Co czynią?
Jakie nowe czyny i dzieła Jezusa Chrystusa odkryłeś w tym fragmencie Ewangelii?
Nauczanie 
Jakie odkryłeś nowe cechy charakteru Pana Jezusa, Jego stylu życia i relacji z Bogiem i z ludźmi?
Jest cierpliwy,łagodny i pokornego serca
Jakie odkryłeś słowa i czyny, które świadczą o BÓSTWIE Pana Jezusa?
łagodny i pokornego serca

Kto i w jaki sposób wyznał wiarę w Jego boską naturę?
Nikt
Jak się modliła ta osoba?
Jak żyła?
Jakie to ma znaczenie dla mojego codziennego życia?

*** MOJE ŻYCIE
Czy moje życie jest podobne do życia Pana Jezusa?
Nie, nie jest
W czym jestem podobny do Pana Jezusa?
W pragnieniu pełnienia woli Ojca
W czym nie jestem podobny do Pana Jezusa?
Brak mi pokory,łagodności,i jest we mnie dużo egoizmu i lenistwa
Dlaczego nie jestem do Niego podobny?
Bo jestem przykuty łańcuchem do lenistwa,obżarstwa,egoizmu i wielu rzeczy o których nie wiem
Co mogę zmienić, a co jest ode mnie niezależne?
Chce walczyć z obżarstwem,lenistwem i egoizmem we mnie, a niezależna ode mnie jest pogoda
Co chciałbyś zmienić?
Powalczyć z obżarstwem
Od czego możesz zacząć?
Od małych porcji i pamiętaniu o warzywach
Co mnie porusza?Moje jarzmo jest miłe, a ciężar lekki.

*** MEDYTACJA
Zdania / słowa do medytacji:Moje jarzmo jest miłe,a ciężar lekki.
1. czyje? Moje
2. moje,co? Moje jarzmo
3. jakie jest moje jarzmo?Moje jarzmo jest miłe
4. jaki jest ciężar? ciężar lekki         
Refleksja po medytacji:
życie z Panem Jezusem staje się łatwe chodź zewnętrznie niewiele sie zmienia
*** KONTEMPLACJA
