#+title: Medytacja
#+date: 21-02-2026

Siglum:Mt 12,1-8 

*** PANORAMA
Gdzie i kiedy rozgrywa się to wydarzenie?
Wśród zbóż
Jakie osoby w nim występują?
Pan Jezuz, Apostołowie, faryzeusze
Słowo klucz:Syn Człowieczy jest panem szabatu

*** OGRODNIK
Co mówią?Kiedy Pan Jezus, Apostołowie i faryzeusze szli przez pole pełne zbóż, uczniowie Pana zaczęli zrywać kłosy i jeść bo byli głodni.
Wtedy faryzeusze powiedzieli do Niego, że Jego uczniowie robią to czego w szabat nie wolno.Na to Pan dał im naukę o szabacie i o tym że to ON
jest panem szabatu.
Co czynią?Broni swoich uczniów przed atakiem faryzeuszy
Jakie nowe czyny i dzieła Jezusa Chrystusa odkryłeś w tym fragmencie Ewangelii? Źe Pan Jezus jest panem szabatu.
Jakie odkryłeś nowe cechy charakteru Pana Jezusa, Jego stylu życia i relacji z Bogiem i z ludźmi? Jest konkretny i sprawiedliwy
Jakie odkryłeś słowa i czyny, które świadczą o BÓSTWIE Pana Jezusa?"Bo panem szabatu jest Syn Człowieczy."
Kto i w jaki sposób wyznał wiarę w Jego boską naturę?Nikt.
Jak się modliła ta osoba?
Jak żyła?
Jakie to ma znaczenie dla mojego codziennego życia?

*** MOJE ŻYCIE
Czy moje życie jest podobne do życia Pana Jezusa?Nie,nie jest.
W czym jestem podobny do Pana Jezusa?W pragnieniu pełnienia woli Ojca.
W czym nie jestem podobny do Pana Jezusa?Zbyt często idę na kompromis
Dlaczego nie jestem do Niego podobny?Z lenistwa.
Co mogę zmienić, a co jest ode mnie niezależne?Chcę walczyć z lenistwem,obżarstwem,i kompromisem
Co chciałbyś zmienić?Pozbyć sie obżarstwa,lenistwa
Od czego możesz zacząć?Od małych porcji i nie podjadania
Co mnie porusza?"Bo panem szabatu jest Syn Człowieczy."

*** MEDYTACJA
Zdania / słowa do medytacji:"Bo panem szabatu jest Syn Człowieczy."
1.bo kim?Bo panem.
2.bo panem czego? Bo panem szabatu.
3.bo kto jest panem szabatu? Bo panem szabatu jest Syn.
4.bo jaki Syn jest panem szabatu? Bo panem szabatu jest Syn Człowieczy.
Refleksja po medytacji:

*** KONTEMPLACJA
