#+title: Medytacja
#+date: 22-02-2026

Siglum:Mt 12,9-21 

*** PANORAMA
Gdzie i kiedy rozgrywa się to wydarzenie? W synagodze
Jakie osoby w nim występują? Pan Jezus, faryzeusze, apostołowie i tłumy
Słowo klucz: dobro

*** OGRODNIK
Co mówią? faryzeusze w synagodze pytają Pana Jezusa, czy wolno w szabat uzdrowić? On im odpowiedział posługując sie przykładem
owcy, która wpadła do dołu,że wolno w szabat dobrze czynić.
Co czynią?Pan Jezus uzdrawia człowieka z uschłą ręką, a faryzeusze po wyjściu z synagogi zaczęli szukać sposobu aby zabić Pana,a On wiedząc o tym odszedł
z tamtąd,a zanim poszło wielu których uzdrowił i prosił by nie czynili go kimś sławnym.
Jakie nowe czyny i dzieła Jezusa Chrystusa odkryłeś w tym fragmencie Ewangelii? Uzdrowienie człowieka z uschłą ręką.
Jakie odkryłeś nowe cechy charakteru Pana Jezusa, Jego stylu życia i relacji z Bogiem i z ludźmi? Odwagę
Jakie odkryłeś słowa i czyny, które świadczą o BÓSTWIE Pana Jezusa? Uzdrowienie człowieka z uschłą ręką.
Kto i w jaki sposób wyznał wiarę w Jego boską naturę? Nikt
Jak się modliła ta osoba?
Jak żyła?
Jakie to ma znaczenie dla mojego codziennego życia?

*** MOJE ŻYCIE
Czy moje życie jest podobne do życia Pana Jezusa? Nie,nie jest.
W czym jestem podobny do Pana Jezusa? W pragnieniu pełnienia woli Ojca
W czym nie jestem podobny do Pana Jezusa? Brak mi odwagi by bronić wiary i swoich poglądów
Dlaczego nie jestem do Niego podobny? strach przed odrzuceniem
Co mogę zmienić, a co jest ode mnie niezależne? prosić o łaskę odważnego stawania w obronie wiary i swoich poglądów 
Co chciałbyś zmienić? być odważnym
Od czego możesz zacząć? odważnie stawać w sytuacji próby wiary
Co mnie porusza?kimś sławnym nie robili

*** MEDYTACJA
Zdania / słowa do medytacji:Lecz upominał ich,żeby Go kimś sławnym nie robili.
1.Lecz co robił? Lecz upominał
2.kogo upominał? upominał ich
3.jak ich upominał?żeby nie robili
4.żeby czego nie robili?żeby kimś nie robili
5.żeby kim nie robili? żeby kimś sławnym nie robili
6.żeby kogo kimś sławnym nie robili? żeby GO kimś sławnym nie robili
Refleksja po medytacji:
ciągle we mnie siedzi i przy różnych okazjach wychodzi chęć bycia sławnym. Oddaję Ci Panie te wszystkie chwile już minione i te przyszłe,
gdy pojawi się pokusa bycia sławnym. Proszę Cię Panie o ducha pokory i serce skrószone. Amen
*** KONTEMPLACJA
