#+title: Medytacja
#+date: 23-02-2026

Siglum: Mt 12,22-37 

*** PANORAMA
Gdzie i kiedy rozgrywa się to wydarzenie? W okolicach synagogi
Jakie osoby w nim występują? Pan Jezus,apostołowie i tłumy
Słowo klucz:Sąd

*** OGRODNIK
Co mówią? Faryzeusze oskarżają Pana,że za sprawą belzebuba usuwa demony. Pan w odpowiedzi dał przykład podzielonego domu,potem powiedział,że kto nie jest z Nim,jest
przeciw Niemu,następnie nauczał o tym że bluźnierstwo przeciw Duchowi Świętemu nie będzie odpuszczone ani na tym świecie ani w przyszłym.Nauczał też o tym że po owocach
poznaje sie drzewo i człowieka.
Co czynią? Pan Jezus uzdrawia człowieka który nie widzi i nie mówi.
Jakie nowe czyny i dzieła Jezusa Chrystusa odkryłeś w tym fragmencie Ewangelii? Uzdrowienie człowieka który nie widzi i nie mówi.
Jakie odkryłeś nowe cechy charakteru Pana Jezusa, Jego stylu życia i relacji z Bogiem i z ludźmi? Mężną argumentację
Jakie odkryłeś słowa i czyny, które świadczą o BÓSTWIE Pana Jezusa? Uzdrowienie człowieka który nie widzi i nie mówi. 
Kto i w jaki sposób wyznał wiarę w Jego boską naturę? nikt
Jak się modliła ta osoba?
Jak żyła?
Jakie to ma znaczenie dla mojego codziennego życia?

*** MOJE ŻYCIE
Czy moje życie jest podobne do życia Pana Jezusa? Nie,nie jest
W czym jestem podobny do Pana Jezusa? Chcę pełnić wolę Ojca
W czym nie jestem podobny do Pana Jezusa? Brak mi męstwa
Dlaczego nie jestem do Niego podobny? Z braku akceptacji samotności
Co mogę zmienić, a co jest ode mnie niezależne? Moge zaakceptować samotność,nie mam wpływu na pogode
Co chciałbyś zmienić? zaakceptować samotność
Od czego możesz zacząć? od modlitwy
Co mnie porusza?Po owocu bowiem poznaje sie drzewo.

*** MEDYTACJA
Zdania / słowa do medytacji: Po owocu bowiem poznaje się drzewo.
1.po czym? Po owocu.
2.co się dzieje po owocu? po owocu bowiem poznaje się.
3.co po owocu poznaje się? po owocu bowiem poznaje się drzewo.
Refleksja po medytacji:

*** KONTEMPLACJA
