#+title: Medytacja
#+date: 26-02-2026

Siglum: Mt 12,38-45

*** PANORAMA
Gdzie i kiedy rozgrywa się to wydarzenie? Nie wiem, nie podano
Jakie osoby w nim występują? Pan Jezus, apostołowie, uczeni w Piśmie i faryzeusze
Słowo klucz:Jonasz

*** OGRODNIK
Co mówią? Faryzeusze i uczeni w Piśmie zarządali od Pana Jezusa, by dał im jakiś znak. On w odpowiedzi przypomniał sprawę
Niniwy i proroka Jonasza, oraz przepowiedział co stanie się z Izraelitami
Co czynią?
Jakie nowe czyny i dzieła Jezusa Chrystusa odkryłeś w tym fragmencie Ewangelii? Nie ulega naciskom
Jakie odkryłeś nowe cechy charakteru Pana Jezusa, Jego stylu życia i relacji z Bogiem i z ludźmi? Jest 
Jakie odkryłeś słowa i czyny, które świadczą o BÓSTWIE Pana Jezusa? Przepowiadanie
Kto i w jaki sposób wyznał wiarę w Jego boską naturę? Nikt
Jak się modliła ta osoba?
Jak żyła?
Jakie to ma znaczenie dla mojego codziennego życia?

*** MOJE ŻYCIE
Czy moje życie jest podobne do życia Pana Jezusa? Nie,nie jest
W czym jestem podobny do Pana Jezusa? W pragnieniu pełnienia woli Ojca
W czym nie jestem podobny do Pana Jezusa? często ulegam naciskom
Dlaczego nie jestem do Niego podobny? brak mi odwagi
Co mogę zmienić, a co jest ode mnie niezależne? Prosić Pana o mężne serce
Co chciałbyś zmienić? Być odważnym
Od czego możesz zacząć? Nie wiem
Co mnie porusza? Zepsute i cudzołożne plemię...

*** MEDYTACJA
Zdania / słowa do medytacji: Zepsute i cudzołożne plemię
1. kto? plemię
2. jakie plemię? zepsute plemię
3. jakie jeszcze plemię? cudzołożne plemię
Refleksja po medytacji:

*** KONTEMPLACJA
