#+title: Medytacja
#+date: 27-02-2026

Siglum: Mt 12, 46-50

*** PANORAMA
Gdzie i kiedy rozgrywa się to wydarzenie? W domu ale nie podano miejscowości
Jakie osoby w nim występują? Pan Jezus, tłumy, jakiś człowiek, apostołowie
Słowo klucz:brat,siostra,matka

*** OGRODNIK
Co mówią?Jakiś człowiek powiedział Panu że na zewnątrz są Jego matka i bracia i chcą z Nim mówić. Pan wskazał na apostołów oraz
otaczające Go tłumy i powiedział że ten kto pełni wolę Ojca, Tego w niebie ten jest Mu matką,siostrą i matką.
Co czynią?
Jakie nowe czyny i dzieła Jezusa Chrystusa odkryłeś w tym fragmencie Ewangelii? Jasne określenie kto jest mu bliski
Jakie odkryłeś nowe cechy charakteru Pana Jezusa, Jego stylu życia i relacji z Bogiem i z ludźmi? Ojciec jest w Jego centrum
Jakie odkryłeś słowa i czyny, które świadczą o BÓSTWIE Pana Jezusa? nie wiem
Kto i w jaki sposób wyznał wiarę w Jego boską naturę?nikt
Jak się modliła ta osoba?
Jak żyła?
Jakie to ma znaczenie dla mojego codziennego życia?

*** MOJE ŻYCIE
Czy moje życie jest podobne do życia Pana Jezusa?Nie nie jest
W czym jestem podobny do Pana Jezusa? w pragnieniu pełnienia woli Ojca niebieskiego
W czym nie jestem podobny do Pana Jezusa? Ojciec niebieski nie jest w moim centrum
Dlaczego nie jestem do Niego podobny? Bo to trudne
Co mogę zmienić, a co jest ode mnie niezależne? Powalczyć o to co trudne
Co chciałbyś zmienić? By Ojciec niebieski był w centrum mojego życia
Od czego możesz zacząć? od dziś
Co mnie porusza?Oto moja matka i moi bracia.

*** MEDYTACJA
Zdania / słowa do medytacji: Oto moja matka i moi bracia.
1.oto kto? oto matka i bracia
2.czyja matka? oto moja matka
3.czyi bracia? moi bracia
Refleksja po medytacji:


*** KONTEMPLACJA
