#+title: Medytacja
#+date: 28-02-2026

Siglum: Mt 13,1-23 

*** PANORAMA
Gdzie i kiedy rozgrywa się to wydarzenie? Nad jeziorem
Jakie osoby w nim występują? Pan Jezus, apostołowie, tłumy
Słowo klucz: przypowieść

*** OGRODNIK
Co mówią?Pan Jezus naucza tłumy w przypowieści o siewcy, gdy skończył, podeszli do Niego Jego uczniowie
i zapytali, dlaczego naucza lud w przypowieściach,a Pan w odpowiedzi przytoczył proroctwo Izajasza, a
następnie wyjaśnił uczniom sens przypowieści o siewcy
Co czynią?Pan Jezus wsiadł do łodzi z powodu dużego tłumu i  nauczał z niej. 
Jakie nowe czyny i dzieła Jezusa Chrystusa odkryłeś w tym fragmencie Ewangelii? Nauczanie w przypowieściach
Jakie odkryłeś nowe cechy charakteru Pana Jezusa, Jego stylu życia i relacji z Bogiem i z ludźmi?tajemniczość
Jakie odkryłeś słowa i czyny, które świadczą o BÓSTWIE Pana Jezusa? Nauczanie w przypowieściach
Kto i w jaki sposób wyznał wiarę w Jego boską naturę? nikt
Jak się modliła ta osoba?
Jak żyła?
Jakie to ma znaczenie dla mojego codziennego życia?

*** MOJE ŻYCIE
Czy moje życie jest podobne do życia Pana Jezusa? Nie, nie jest
W czym jestem podobny do Pana Jezusa? W pragnieniu pełnienia woli Ojca niebieskiego
W czym nie jestem podobny do Pana Jezusa? Jestem przywiązany do tego świata
Dlaczego nie jestem do Niego podobny? Boję się wejść w to co nie znane
Co mogę zmienić, a co jest ode mnie niezależne? zaufać do końca, bezgranicznie Panu Jezusowi
Co chciałbyś zmienić? Wszystko
Od czego możesz zacząć? Mniej komputera, a więcej książki, spaceru itp
Co mnie porusza? zagon z ostami

*** MEDYTACJA
Zdania / słowa do medytacji: Osty wybujały i zagłuszyły je.
1.co? osty
2.co osty zrobiły? osty wybujały
3.i co jeszcze osty zrobiły? i zagłuszyły
4.co zagłuszyły osty? osty zagłuszyły ziarna czyli naukę o królestwie
Refleksja po medytacji:
ograniczyć komputer, i zacząć medytacje nad każdym zdaniem z tekstu od jutra w miarę możliwości

*** KONTEMPLACJA
